version: "3.9"

services:
  exporter:
    image: ghcr.io/rubentalstra/librechat-prom-exporter:latest
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus

volumes:
  prometheus_data: