name: CD
on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check for source changes
        id: changes
        uses: dorny/paths-filter@v3
        with:
          filters: |
            src:
              - 'src/**'
            dockerfile:
              - 'Dockerfile'

      - name: Set up Docker Buildx
        if: steps.changes.outputs.src == 'true' || steps.changes.outputs.dockerfile == 'true'
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        if: steps.changes.outputs.src == 'true' || steps.changes.outputs.dockerfile == 'true'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build and push image when pushing to main branch (only "latest")
      - name: Build and push Docker image (latest)
        if: github.ref == 'refs/heads/main' && (steps.changes.outputs.src == 'true' || steps.changes.outputs.dockerfile == 'true')
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ghcr.io/${{ github.repository }}:latest

      # Build and push image when pushing a version tag.
      # This step tags the image with both the version (e.g. "v1.2.3") and "latest".
      - name: Build and push Docker image (version tag)
        if: startsWith(github.ref, 'refs/tags/v') && (steps.changes.outputs.src == 'true' || steps.changes.outputs.dockerfile == 'true')
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ghcr.io/${{ github.repository }}:${{ github.ref_name }}
            ghcr.io/${{ github.repository }}:latest