name: CD
on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]

permissions:
  contents: read
  packages: write

jobs:
  build_linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Linux image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          # Append "-linux" to the tag so we can differentiate when merging the manifest
          tags: ghcr.io/${{ github.repository }}:${{ github.ref_name }}-linux

  build_windows:
    runs-on: windows-2019
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Windows image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          push: true
          platforms: windows/amd64
          # Append "-windows" to the tag so we can differentiate when merging the manifest
          tags: ghcr.io/${{ github.repository }}:${{ github.ref_name }}-windows

  manifest:
    runs-on: ubuntu-latest
    needs: [build_linux, build_windows]
    steps:
      - name: Create and push multi-arch manifest
        run: |
          docker manifest create ghcr.io/${{ github.repository }}:${{ github.ref_name }} \
            ghcr.io/${{ github.repository }}:${{ github.ref_name }}-linux \
            ghcr.io/${{ github.repository }}:${{ github.ref_name }}-windows
          docker manifest push ghcr.io/${{ github.repository }}:${{ github.ref_name }}