name: Code Quality
on:
  pull_request:
    branches: [ main ]

jobs:
  static-analysis:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint and save results
        id: eslint
        run: |
          npx eslint . --ext .ts --format json > eslint_results.json || true

      - name: Run depcheck and save results
        id: depcheck
        run: |
          npx depcheck > depcheck_results.txt || true

      - name: Run ts-prune and save results
        id: tsprune
        run: |
          npx ts-prune > tsprune_results.txt || true

      - name: Upload Code Quality Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: code-quality-results
          path: |
            eslint_results.json
            depcheck_results.txt
            tsprune_results.txt