# Repository Ruleset: Enforce CI and Code Quality checks on the main branch
ruleset:
  name: "Protect main branch"
  target:
    branch_patterns:
      - "main"
  requires:
    status_checks:
      strict: true
      contexts:
        - "build_test"       # Status context from your build, lint, compile, test job
        - "static_analysis"  # Status context from your static analysis job
    reviews:
      dismiss_stale_reviews: true
      require_code_owner_reviews: true
      required_approving_review_count: 1
    restrictions:
      users: []
      teams: []